// Generated by scripts/export_watchlist.py from config/watchlist.yaml. Do not edit.
globalThis.SummerandDefaultWatchlist = {
  "stoplist": [
    "A",
    "AI",
    "ALL",
    "API",
    "APT",
    "ARE",
    "AT",
    "ATH",
    "BE",
    "BIG",
    "CAN",
    "CEO",
    "CEX",
    "CFO",
    "CFTC",
    "CPI",
    "CTO",
    "DAO",
    "DEX",
    "DOJ",
    "ETF",
    "ETFs",
    "EU",
    "FBI",
    "FED",
    "FOMC",
    "FOR",
    "GDP",
    "GO",
    "HAS",
    "I",
    "IMF",
    "IPO",
    "IT",
    "LINK",
    "NEAR",
    "NEW",
    "NFT",
    "NOW",
    "OK",
    "ON",
    "ONE",
    "OP",
    "OPEN",
    "PCE",
    "Q1",
    "Q2",
    "Q3",
    "Q4",
    "S",
    "SEC",
    "SO",
    "TV",
    "TVL",
    "UK",
    "UNI",
    "US",
    "USA",
    "USD",
    "USDC",
    "USDT"
  ],
  "symbols": [
    {
      "aliases": [
        "Bitcoin",
        "bitcoin",
        "BTC"
      ],
      "asset_class": "crypto",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "BTC"
    },
    {
      "aliases": [
        "Ethereum",
        "Ether"
      ],
      "asset_class": "crypto",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [
        "Zurich"
      ],
      "symbol": "ETH"
    },
    {
      "aliases": [
        "Solana"
      ],
      "asset_class": "crypto",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "SOL"
    },
    {
      "aliases": [
        "Ripple"
      ],
      "asset_class": "crypto",
      "bare": true,
      "context": "crypto",
      "legacy": [],
      "not_before": [],
      "symbol": "XRP"
    },
    {
      "aliases": [
        "Dogecoin",
        "dogecoin"
      ],
      "asset_class": "crypto",
      "bare": false,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "DOGE"
    },
    {
      "aliases": [
        "Cardano"
      ],
      "asset_class": "crypto",
      "bare": false,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "ADA"
    },
    {
      "aliases": [
        "Avalanche"
      ],
      "asset_class": "crypto",
      "bare": true,
      "context": "crypto",
      "legacy": [],
      "not_before": [],
      "symbol": "AVAX"
    },
    {
      "aliases": [
        "Polkadot"
      ],
      "asset_class": "crypto",
      "bare": false,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "DOT"
    },
    {
      "aliases": [
        "Chainlink"
      ],
      "asset_class": "crypto",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "LINK"
    },
    {
      "aliases": [
        "Uniswap"
      ],
      "asset_class": "crypto",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "UNI"
    },
    {
      "aliases": [
        "Litecoin"
      ],
      "asset_class": "crypto",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "LTC"
    },
    {
      "aliases": [],
      "asset_class": "crypto",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "BNB"
    },
    {
      "aliases": [
        "Tron",
        "TRON"
      ],
      "asset_class": "crypto",
      "bare": true,
      "context": "crypto",
      "legacy": [],
      "not_before": [],
      "symbol": "TRX"
    },
    {
      "aliases": [
        "Toncoin"
      ],
      "asset_class": "crypto",
      "bare": false,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "TON"
    },
    {
      "aliases": [],
      "asset_class": "crypto",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "SUI"
    },
    {
      "aliases": [
        "Hyperliquid"
      ],
      "asset_class": "crypto",
      "bare": false,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "HYPE"
    },
    {
      "aliases": [],
      "asset_class": "crypto",
      "bare": true,
      "context": null,
      "legacy": [
        "MATIC"
      ],
      "not_before": [],
      "symbol": "POL"
    },
    {
      "aliases": [
        "Apple"
      ],
      "asset_class": "equity",
      "bare": true,
      "context": "market",
      "legacy": [],
      "not_before": [],
      "symbol": "AAPL"
    },
    {
      "aliases": [
        "Microsoft"
      ],
      "asset_class": "equity",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "MSFT"
    },
    {
      "aliases": [
        "Nvidia",
        "NVIDIA"
      ],
      "asset_class": "equity",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "NVDA"
    },
    {
      "aliases": [
        "Meta Platforms",
        "Meta"
      ],
      "asset_class": "equity",
      "bare": false,
      "context": "market",
      "legacy": [],
      "not_before": [],
      "symbol": "META"
    },
    {
      "aliases": [
        "Coinbase"
      ],
      "asset_class": "equity",
      "bare": false,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "COIN"
    },
    {
      "aliases": [
        "Tesla"
      ],
      "asset_class": "equity",
      "bare": true,
      "context": "market",
      "legacy": [],
      "not_before": [],
      "symbol": "TSLA"
    },
    {
      "aliases": [
        "Amazon"
      ],
      "asset_class": "equity",
      "bare": true,
      "context": "market",
      "legacy": [],
      "not_before": [],
      "symbol": "AMZN"
    },
    {
      "aliases": [
        "Alphabet",
        "Google"
      ],
      "asset_class": "equity",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "GOOGL"
    },
    {
      "aliases": [
        "MicroStrategy"
      ],
      "asset_class": "equity",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "MSTR"
    },
    {
      "aliases": [
        "Robinhood"
      ],
      "asset_class": "equity",
      "bare": false,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "HOOD"
    },
    {
      "aliases": [
        "JPMorgan",
        "JPMorgan Chase"
      ],
      "asset_class": "equity",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "JPM"
    },
    {
      "aliases": [
        "Goldman Sachs"
      ],
      "asset_class": "equity",
      "bare": false,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "GS"
    },
    {
      "aliases": [
        "S&P 500"
      ],
      "asset_class": "equity",
      "bare": true,
      "context": null,
      "legacy": [],
      "not_before": [],
      "symbol": "SPY"
    }
  ]
};
