RAW_NEWS = "raw_news"
CLEAN_NEWS = "clean_news"
TICKS_CRYPTO = "ticks_crypto"
TICKS_EQUITY = "ticks_equity"
BARS = "bars"
RANKED_STORIES = "ranked_stories"
BRIEFS = "briefs"

ALL = [RAW_NEWS, CLEAN_NEWS, TICKS_CRYPTO, TICKS_EQUITY, BARS, RANKED_STORIES, BRIEFS]
PIPELINE_INPUTS = [CLEAN_NEWS, BARS, TICKS_CRYPTO, TICKS_EQUITY]
