"""Write extension/shared/watchlist.default.js from config/watchlist.yaml.

The extension fetches /api/watchlist when it can reach the server; this copy is what the content
script uses before that (or when the server is down). tests/test_extension_sync.py checks it is
current."""

import json
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT))

from summerand.config import load_watchlist  # noqa: E402

OUT = ROOT / "extension" / "shared" / "watchlist.default.js"


def render() -> str:
    data = load_watchlist(ROOT / "config").to_json()
    body = json.dumps(data, indent=2, sort_keys=True)
    return (
        "// Generated by scripts/export_watchlist.py from config/watchlist.yaml. Do not edit.\n"
        f"globalThis.SummerandDefaultWatchlist = {body};\n"
    )


if __name__ == "__main__":
    OUT.write_text(render())
    print(f"wrote {OUT}")
